# Generated by Django 4.2 on 2024-01-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Msgs_Api', '0003_meesagetype_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Msgs',
        ),
        migrations.DeleteModel(
            name='MsgsTypes',
        ),
    ]
