# Generated by Django 4.2 on 2024-01-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Msgs_Api', '0004_delete_msgs_delete_msgstypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
