# Generated by Django 4.2 on 2024-02-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Msgs_Api', '0005_alter_messages_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='added_dates',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='added_timestampss',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='today_dates',
            field=models.DateField(default=None, null=True),
        ),
    ]
