# Generated by Django 4.2 on 2024-02-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Msgs_Api', '0006_messages_added_dates_messages_added_timestampss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='added_dates',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='added_timestampss',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='today_dates',
        ),
    ]
