# Generated by Django 4.2 on 2024-02-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Msgs_Api', '0008_messages_created_at_messages_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
