# Generated by Django 4.2 on 2024-02-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Msgs_Api', '0009_alter_messages_created_at_alter_messages_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='created_at_new_msgs_text',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='new_msgs_text',
            field=models.CharField(default=1, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='updated_at_new_msgs_text',
            field=models.DateField(null=True),
        ),
    ]
