# Generated by Django 4.2 on 2024-02-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Msgs_Api', '0010_messages_created_at_new_msgs_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meesagetype',
            name='created_at_new_msgs_text',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='meesagetype',
            name='new_msgs_text',
            field=models.CharField(default=1, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='meesagetype',
            name='updated_at_new_msgs_text',
            field=models.DateField(null=True),
        ),
    ]
