# Generated by Django 4.2 on 2024-03-05 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Msgs_Api', '0011_meesagetype_created_at_new_msgs_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meesagetype',
            name='my_time_auto',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='my_time_auto',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
