# Generated by Django 4.2 on 2024-10-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Msgs_Api', '0012_meesagetype_my_time_auto_messages_my_time_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='day_num',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='messages',
            name='new_msgs',
            field=models.CharField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='messages',
            name='new_msgs_text',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
