# Generated by Django 4.2 on 2024-10-27 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Msgs_Api', '0013_messages_day_num_alter_messages_new_msgs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackUp_Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MessageName', models.CharField(max_length=1000, null=True)),
                ('new_msgs', models.CharField(default=1, max_length=2)),
                ('ID_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Msgs_Api.meesagetype')),
            ],
        ),
    ]
