# Generated by Django 4.2 on 2024-11-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Msgs_Api', '0014_backup_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackUp_Messages',
        ),
    ]
