# Generated by Django 4.2 on 2024-12-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Msgs_Api', '0015_delete_backup_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='MessageName',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
