# Generated by Django 4.2 on 2024-12-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Msgs_Api', '0016_alter_messages_messagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='MessageName',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
