# Generated by Django 4.2 on 2024-02-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Img_Api', '0013_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgs',
            name='added_dates',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='imgs',
            name='added_timestampss',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='imgs',
            name='today_dates',
            field=models.DateField(default=None, null=True),
        ),
    ]
