# Generated by Django 4.2 on 2024-02-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Img_Api', '0014_imgs_added_dates_imgs_added_timestampss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgs',
            name='added_dates',
        ),
        migrations.RemoveField(
            model_name='imgs',
            name='added_timestampss',
        ),
        migrations.RemoveField(
            model_name='imgs',
            name='today_dates',
        ),
    ]
