# Generated by Django 4.2 on 2024-03-05 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Img_Api', '0016_imgs_created_at_imgs_created_at_new_msgs_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgs',
            name='my_time_auto',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
