# Generated by Django 4.2 on 2024-03-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Img_Api', '0017_imgs_my_time_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgs',
            name='my_time_auto',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
