# Generated by Django 4.2 on 2024-04-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Img_Api', '0019_imgsnokat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgsnokat',
            name='pic',
            field=models.ImageField(upload_to='nokat/'),
        ),
    ]
