# Generated by Django 4.2 on 2024-04-21 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Img_Api', '0020_alter_imgsnokat_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='NokatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NokatTypes', models.CharField(max_length=100, null=True)),
                ('new_img', models.CharField(default=1, max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='imgsnokat',
            name='ID_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Img_Api.imagetype'),
        ),
    ]
