# Generated by Django 4.2 on 2024-04-22 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Img_Api', '0021_nokattype_imgsnokat_id_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nokattype',
            old_name='NokatTypes',
            new_name='Nokat_Typ',
        ),
        migrations.AlterField(
            model_name='imgsnokat',
            name='ID_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Img_Api.nokattype'),
        ),
    ]
