# Generated by Django 4.2 on 2024-04-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Img_Api', '0022_rename_nokattypes_nokattype_nokat_typ_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgsnokat',
            name='NokatTypes',
        ),
    ]
