# Generated by Django 4.2 on 2024-04-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Img_Api', '0023_remove_imgsnokat_nokattypes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgsNokat',
        ),
    ]
