# Generated by Django 4.2 on 2024-04-22 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Img_Api', '0024_delete_imgsnokat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgsNokat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_nokat', models.CharField(default=1, max_length=2)),
                ('pic', models.ImageField(upload_to='nokat/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('new_msgs_text', models.CharField(default=1, max_length=2, null=True)),
                ('created_at_new_msgs_text', models.DateField(null=True)),
                ('updated_at_new_msgs_text', models.DateField(null=True)),
                ('my_time_auto', models.TimeField(auto_now_add=True)),
                ('ID_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Img_Api.nokattype')),
            ],
        ),
    ]
