# Generated by Django 4.2 on 2024-04-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Img_Api', '0025_imgsnokat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgsNokat',
        ),
        migrations.DeleteModel(
            name='NokatType',
        ),
    ]
