# Generated by Django 4.2 on 2024-02-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nokat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NokatTypes', models.CharField(max_length=100, null=True)),
                ('new_nokat', models.CharField(default=1, max_length=2)),
                ('NokatName', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
