# Generated by Django 4.2 on 2024-02-26 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nokat',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nokat',
            name='created_at_new_msgs_text',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='nokat',
            name='new_msgs_text',
            field=models.CharField(default=1, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='nokat',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nokat',
            name='updated_at_new_msgs_text',
            field=models.DateField(null=True),
        ),
    ]
