# Generated by Django 4.2 on 2024-04-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0004_imgsnokat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgsNokat',
        ),
    ]
