# Generated by Django 4.2 on 2024-04-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0006_imagesnokat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesnokat',
            name='NokatTypes',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nokat',
            name='NokatTypes',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
