# Generated by Django 4.2 on 2024-04-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0007_alter_imagesnokat_nokattypes_alter_nokat_nokattypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesnokat',
            name='new_msgs_text',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='imagesnokat',
            name='new_nokat',
            field=models.BooleanField(default=True),
        ),
    ]
