# Generated by Django 4.2 on 2024-04-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0010_alter_imagesnokat_new_msgs_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagesNokat',
        ),
    ]
