# Generated by Django 4.2 on 2024-04-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0012_imagesnokat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesnokat',
            name='new_msgs_text',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='imagesnokat',
            name='new_nokat',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], max_length=2, null=True),
        ),
    ]
