# Generated by Django 4.2 on 2024-04-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0013_alter_imagesnokat_new_msgs_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesnokat',
            name='NokatTypes',
        ),
    ]
