# Generated by Django 4.2 on 2024-04-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0014_remove_imagesnokat_nokattypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesnokat',
            name='new_msgs_text',
            field=models.CharField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='imagesnokat',
            name='new_nokat',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
