# Generated by Django 4.2 on 2024-04-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0016_alter_imagesnokat_new_msgs_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesnokat',
            name='new_msgs_text',
            field=models.CharField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='imagesnokat',
            name='new_nokat',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
