# Generated by Django 4.2 on 2024-04-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0017_alter_imagesnokat_new_msgs_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesnokat',
            old_name='new_msgs_text',
            new_name='img_show',
        ),
        migrations.RenameField(
            model_name='imagesnokat',
            old_name='new_nokat',
            new_name='new_img',
        ),
    ]
