# Generated by Django 4.2 on 2024-04-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0018_rename_new_msgs_text_imagesnokat_img_show_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesnokat',
            name='img_show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='imagesnokat',
            name='new_img',
            field=models.BooleanField(default=True),
        ),
    ]
