# Generated by Django 4.2 on 2024-04-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0021_alter_imagesnokat_img_show_alter_imagesnokat_new_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesnokat',
            name='img_show',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], default=1),
        ),
        migrations.AlterField(
            model_name='imagesnokat',
            name='new_img',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], default=1),
        ),
    ]
