# Generated by Django 4.2 on 2024-04-24 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0022_alter_imagesnokat_img_show_alter_imagesnokat_new_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTypeNokat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImgTypes', models.CharField(max_length=100, null=True)),
                ('new_img', models.CharField(default=1, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ImgsNokat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
                ('new_img', models.CharField(default=1, max_length=2, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('show_hide', models.CharField(default=1, max_length=2, null=True)),
                ('created_at_new_msgs_text', models.DateField(null=True)),
                ('updated_at_new_msgs_text', models.DateField(null=True)),
                ('my_time_auto', models.TimeField(auto_now_add=True)),
                ('ID_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nokat_api.imagetypenokat')),
            ],
        ),
    ]
