# Generated by Django 4.2 on 2024-04-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0023_imagetypenokat_imgsnokat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgsnokat',
            name='ID_Type',
        ),
        migrations.DeleteModel(
            name='ImageTypeNokat',
        ),
        migrations.DeleteModel(
            name='ImgsNokat',
        ),
    ]
