# Generated by Django 4.2 on 2024-06-23 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0024_remove_imgsnokat_id_type_delete_imagetypenokat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NokatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoktTypes', models.CharField(max_length=100, null=True)),
                ('new_Nokat', models.CharField(default=1, max_length=2)),
                ('new_Nokat_show', models.CharField(default=1, max_length=2, null=True)),
                ('created_at_new_msgs_text', models.DateField(null=True)),
                ('updated_at_new_msgs_text', models.DateField(null=True)),
                ('my_time_auto', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='nokat',
            old_name='new_msgs_text',
            new_name='new_msgs_show',
        ),
        migrations.AddField(
            model_name='nokat',
            name='ID_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nokat_api.nokattype'),
        ),
    ]
