# Generated by Django 4.2 on 2024-06-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0025_nokattype_rename_new_msgs_text_nokat_new_msgs_show_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nokat',
        ),
    ]
