# Generated by Django 4.2 on 2024-06-23 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0026_delete_nokat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nokat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NokatTypes', models.CharField(max_length=1000, null=True)),
                ('new_nokat', models.CharField(default=1, max_length=2)),
                ('NokatName', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('new_msgs_show', models.CharField(default=1, max_length=2, null=True)),
                ('created_at_new_msgs_text', models.DateField(null=True)),
                ('updated_at_new_msgs_text', models.DateField(null=True)),
                ('my_time_auto', models.TimeField(auto_now_add=True)),
                ('ID_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nokat_api.nokattype')),
            ],
        ),
    ]
