# Generated by Django 4.2 on 2024-06-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0027_nokat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nokat',
        ),
        migrations.DeleteModel(
            name='NokatType',
        ),
    ]
