# Generated by Django 4.2 on 2024-06-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0029_nokattype_nokat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nokat',
            old_name='ID_Type',
            new_name='NokatID_Type',
        ),
        migrations.AlterField(
            model_name='nokat',
            name='new_msgs_show',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='nokattype',
            name='new_Nokat_show',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
