# Generated by Django 4.2 on 2024-06-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0030_rename_id_type_nokat_nokatid_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nokat',
            old_name='NokatID_Type',
            new_name='ID_Type',
        ),
    ]
