# Generated by Django 4.2 on 2024-06-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0032_alter_nokat_new_msgs_show_alter_nokat_new_nokat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nokat',
            name='new_msgs_show',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nokat',
            name='new_nokat',
            field=models.IntegerField(default=1),
        ),
    ]
