# Generated by Django 4.2 on 2024-06-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0033_alter_nokat_new_msgs_show_alter_nokat_new_nokat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nokat',
            name='ID_Type',
        ),
    ]
