# Generated by Django 4.2 on 2024-06-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nokat_api', '0035_nokat_id_type_alter_nokattype_new_nokat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nokat',
            name='NokatTypes',
        ),
    ]
